# Site settings
email: 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Coast to Coast
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Landon Getz
profile_img: /assets/LG_Edit2.jpg
profile: Landon Getz is a Medicine Hat, Alberta Native living in Nova Scotia.
social:
  twitter: https://twitter.com/LandonGetz

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
